ASPCoreCurd_EmployeeDetails/Models/AddEmpModelView.cs
namespace ASPCoreCurd_EmployeeDetails.Models
{
    public class AddEmpModelView
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public double Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }
    }
}

ASPCoreCurd_EmployeeDetails/Models/EmpModel.cs
namespace ASPCoreCurd_EmployeeDetails.Models
{
    public class EmpModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public double Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }
    }
}

ASPCoreCurd_EmployeeDetails/Models/ErrorViewModel.cs
namespace ASPCoreCurd_EmployeeDetails.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPCoreCurd_EmployeeDetails/Models/ViewEmpModel.cs
namespace ASPCoreCurd_EmployeeDetails.Models
{
    public class ViewEmpModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public double Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }
    }
}

ASPCoreCurd_EmployeeDetails/Controllers/EmpController.cs
using ASPCoreCurd_EmployeeDetails.Data;
using ASPCoreCurd_EmployeeDetails.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ASPCoreCurd_EmployeeDetails.Controllers
{
    public class EmpController : Controller
    {
        private readonly ApplicationDBContext _applicationDBContext;
        public EmpController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var EmpDetails = _applicationDBContext.EmpDetails.ToList();
            return View(EmpDetails);
        }

        [HttpGet]
        public IActionResult View(Guid id)
        {
            var ViewEmpDetails = _applicationDBContext.EmpDetails.Where(x => x.Id == id).FirstOrDefault();
            if (ViewEmpDetails != null)
            {
                ViewEmpModel viewEmpModel = new ViewEmpModel()
                {
                    Id = ViewEmpDetails.Id,
                    Name = ViewEmpDetails.Name,
                    Email = ViewEmpDetails.Email,
                    Salary = ViewEmpDetails.Salary,
                    DateOfBirth = ViewEmpDetails.DateOfBirth,
                    Department = ViewEmpDetails.Department
                };

                return View(ViewEmpDetails);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete(EmpModel empModel)
        {
            var empDetails = _applicationDBContext.EmpDetails.Find(empModel.Id);
            if (empDetails != null)
            {
                _applicationDBContext.EmpDetails.Remove(empDetails);
                _applicationDBContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Add(AddEmpModelView addEmpModelView)
        {
            EmpModel empModel = new EmpModel()
            {
                Id = Guid.NewGuid(),
                Name= addEmpModelView.Name,
                Email= addEmpModelView.Email,
                Salary= addEmpModelView.Salary,
                DateOfBirth= addEmpModelView.DateOfBirth,
                Department= addEmpModelView.Department
            };

            _applicationDBContext.EmpDetails.Add(empModel);
            _applicationDBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult View(ViewEmpModel viewEmpModel)
        {
            var emp = _applicationDBContext.EmpDetails.Find(viewEmpModel.Id);
            if (emp != null)
            {
                emp.Email = viewEmpModel.Email;
                emp.Name= viewEmpModel.Name;
                emp.Salary= viewEmpModel.Salary;
                emp.DateOfBirth= viewEmpModel.DateOfBirth;
                emp.Department= viewEmpModel.Department;

                _applicationDBContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ASPCoreCurd_EmployeeDetails/Controllers/HomeController.cs
using ASPCoreCurd_EmployeeDetails.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPCoreCurd_EmployeeDetails.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPCoreCurd_EmployeeDetails/Views/Emp/Add.cshtml
@model ASPCoreCurd_EmployeeDetails.Models.AddEmpModelView
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Register Details</h1>
<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="">Emp Name</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Enter Name">
    </div>
    <div class="mb-3">
        <label for="">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" placeholder="Enter Email">
    </div>
    <div class="mb-3">
        <label for="">Salary</label>
        <input type="number" class="form-control" asp-for="Salary" placeholder="Enter Salary">
    </div>
    <div class="mb-3">
        <label for="">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth" placeholder="Enter DOB">
    </div>
    <div class="mb-3">
        <label for="">Department</label>
        <input type="text" class="form-control" asp-for="Department" placeholder="Enter Department">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ASPCoreCurd_EmployeeDetails/Views/Emp/Index.cshtml
@model List<ASPCoreCurd_EmployeeDetails.Models.EmpModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Emp Details</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Salary</th>
            <th>DateOfBirth</th>
            <th>Department</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Email</td>
            <td>@item.Salary</td>
            <td>@item.DateOfBirth</td>
            <td>@item.Department</td>
            <td><a href="Emp/View/@item.Id">View</a></td>
            <td><a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-route-id=@item.Id asp-action="View">EmpDetails</a></td>
        </tr>
        }
    </tbody>

</table>

ASPCoreCurd_EmployeeDetails/Views/Emp/View.cshtml
@model ASPCoreCurd_EmployeeDetails.Models.EmpModel

@{
}

<h1>Update Details</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="">Emp Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="">Emp Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>
    <div class="mb-3">
        <label for="">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>
    <div class="mb-3">
        <label for="">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

    <button type="submit" asp-area="" asp-action="Delete" asp-controller="Emp" class="btn btn-danger">Delete</button>
</form>

ASPCoreCurd_EmployeeDetails/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPCoreCurd_EmployeeDetails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPCoreCurd_EmployeeDetails</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPCoreCurd_EmployeeDetails.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPCoreCurd_EmployeeDetails</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Add">Add Emp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">EmpDetails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPCoreCurd_EmployeeDetails - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>